# Generated by Django 5.2.3 on 2026-06-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_updated_at_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_employee',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='assignment_score',
            field=models.FloatField(default=0),
        ),
    ]
