# Generated by Django 5.2.3 on 2026-06-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_assigned_employee_task_assignment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_position',
            field=models.CharField(default='Junior', max_length=20),
        ),
    ]
