# Generated by Django 5.2.3 on 2026-06-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_required_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_employee',
            field=models.IntegerField(default=0),
        ),
    ]
