# Generated by Django 6.0.6 on 2026-06-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior'), ('Team Lead', 'Team Lead')], max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('skills', models.TextField(help_text='Example: Python, SQL, React')),
                ('experience', models.IntegerField(default=0)),
                ('performance_score', models.FloatField(default=0)),
                ('current_workload', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
    ]
