# Generated by Django 5.2.3 on 2026-06-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ai_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
